# Generated by Django 5.2 on 2025-04-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mbtiresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuestionnaireResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField()),
                ('result_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('professions', models.JSONField()),
            ],
        ),
    ]
